#!/bin/bash
DEBUG="-g"
CC="g++"
CCFLAGS="-Wall -c `pkg-config --cflags glfw3` $DEBUG"

for i in $@; do 
  $CC -M $i 2>/dev/null | tr ' ' '\n' | grep -ve "^$" | grep -ve "^.$"  | grep -ve "^/" | xargs
  echo "	$CC $CCFLAGS `basename $i` -o `basename $i | sed s/cpp/o/`"
  echo
done
